name: 8.1 Build
on:
  push:
    branches:
      - 'release/8.1.*'

jobs:
  multibuild_matrix:
    strategy:
      matrix:
        build_target:
          - 8_1-full
          - 8_1-slim
    uses: thirdgen88/ignition-docker/.github/workflows/multibuild.yml@main
    with:
      build_target: ${{ matrix.build_target }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
