name: 7.9 Build
on:
  push:
    branches:
      - 'release/7.9.*'

jobs:
  call-multibuild:
    uses: thirdgen88/ignition-docker/.github/workflows/multibuild.yml@main
    with:
      build_target: 7_9
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
